name: namui_wam
description: "Namui Wam - Aplicación educativa para aprender números en Namtrik"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  audioplayers: ^6.2.0
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/
    - assets/audio/activity/
    - assets/audio/namtrik_numbers/
    - assets/images/
    - assets/images/clocks/
    - assets/data/
    - assets/data/namtrik_numbers.json
    - assets/data/namtrik_hours.json
